# Generated by Django 2.2.2 on 2019-07-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_title', models.CharField(max_length=200)),
                ('Category_url', models.CharField(max_length=200)),
                ('category_description', models.CharField(max_length=200)),
                ('parent_id', models.IntegerField()),
            ],
        ),
    ]
