# Generated by Django 2.2.2 on 2019-07-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorymanagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='parent_id',
            new_name='parentid',
        ),
        migrations.RemoveField(
            model_name='category',
            name='Category_title',
        ),
        migrations.RemoveField(
            model_name='category',
            name='Category_url',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_description',
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
