# Generated by Django 2.2.2 on 2019-07-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorymanagement', '0004_auto_20190701_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parentid',
            field=models.IntegerField(default=0),
        ),
    ]
