# Generated by Django 2.2.2 on 2019-07-02 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorymanagement', '0005_auto_20190701_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parentid',
            field=models.IntegerField(),
        ),
    ]
