# Generated by Django 2.2.2 on 2019-07-02 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorymanagement', '0007_auto_20190702_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parentid',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='categorymanagement.Category'),
        ),
    ]
