# Generated by Django 2.2.2 on 2019-07-02 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorymanagement', '0009_auto_20190702_0706'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-id']},
        ),
    ]
