# Generated by Django 2.2.2 on 2019-06-25 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('Tittle', models.CharField(help_text='Enter Tittle', max_length=20)),
                ('description', models.TextField(help_text='Enter a brief description of the book', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/')),
                ('Title', models.CharField(help_text='Enter Tittle', max_length=20)),
                ('des', models.TextField(help_text='Enter a brief description of the book', max_length=1000)),
                ('icons', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Headings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Services', models.CharField(help_text='Enter heading', max_length=20)),
                ('About', models.CharField(help_text='Enter heading', max_length=20)),
                ('Features', models.CharField(help_text='Enter heading', max_length=20)),
                ('Team', models.CharField(help_text='Enter heading', max_length=20)),
                ('Pricing', models.CharField(help_text='Enter heading', max_length=20)),
                ('Contact', models.CharField(help_text='Enter heading', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icons2', models.ImageField(upload_to='images/')),
                ('price', models.IntegerField(help_text='Enter price')),
                ('Title2', models.CharField(help_text='Enter Tittle', max_length=20)),
                ('details', models.TextField(help_text='Enter a brief description of the book', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icons', models.ImageField(upload_to='images/')),
                ('name', models.CharField(help_text='Enter heading', max_length=20)),
                ('summary', models.TextField(help_text='Enter a brief description of the book', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(upload_to='images/')),
                ('name1', models.CharField(help_text='Enter Tittle', max_length=20)),
                ('Title1', models.CharField(help_text='Enter Tittle', max_length=20)),
                ('des1', models.TextField(help_text='Enter a brief description of the book', max_length=1000)),
                ('icons1', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img2', models.ImageField(upload_to='images/')),
                ('name2', models.CharField(help_text='Enter Tittle', max_length=20)),
                ('Title3', models.CharField(help_text='Enter Tittle', max_length=20)),
                ('des3', models.TextField(help_text='Enter a brief description of the book', max_length=1000)),
            ],
        ),
    ]
