# Generated by Django 2.2.2 on 2019-06-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fusion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name3', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('des4', models.TextField(help_text='Enter a brief description of the book', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img5', models.ImageField(upload_to='images/')),
                ('p', models.TextField(help_text='Enter a brief description', max_length=1000)),
                ('h', models.CharField(max_length=20)),
                ('d', models.TextField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='about',
            name='p1',
            field=models.CharField(default=1, help_text='Enter small text', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='services',
            name='icons',
            field=models.CharField(choices=[('settings', 'fa fa-cog'), ('design', 'fa fa-line-chart'), ('customize', 'fa fa-user'), ('ui', 'fa fa-align-justify'), ('app', 'fa fa-android'), ('ufrnd', 'fa fa-sign-language')], max_length=1),
        ),
    ]
