# Generated by Django 2.2.2 on 2019-06-25 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fusion', '0003_auto_20190625_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='des4',
            new_name='message',
        ),
    ]
