# Generated by Django 2.2.2 on 2019-06-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fusion', '0005_auto_20190625_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Featuresimg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='features',
            name='img',
        ),
        migrations.AlterField(
            model_name='features',
            name='icons',
            field=models.CharField(choices=[('settings', 'fa fa-cog'), ('design', 'fa fa-line-chart'), ('customize', 'fa fa-user'), ('ui', 'fa fa-align-justify'), ('app', 'fa fa-android'), ('ufrnd', 'fa fa-sign-language')], max_length=100),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='icons2',
            field=models.CharField(choices=[('pro', 'fa fa-rocket'), ('plus', 'fa fa-star-half-o'), ('primium', 'fa fa-star-o')], max_length=100),
        ),
    ]
