# Generated by Django 2.2.2 on 2019-06-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fusion', '0007_featuresimg_titl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Featuresrght',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(help_text='Enter Tittle', max_length=20)),
                ('des', models.TextField(help_text='Enter a brief description of the book', max_length=1000)),
                ('icons', models.CharField(choices=[('settings', 'fa fa-cog'), ('design', 'fa fa-line-chart'), ('customize', 'fa fa-user'), ('ui', 'fa fa-align-justify'), ('app', 'fa fa-android'), ('ufrnd', 'fa fa-sign-language')], max_length=100)),
            ],
        ),
    ]
