# Generated by Django 2.2.2 on 2019-06-26 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fusion', '0011_auto_20190626_0741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='icons11',
        ),
        migrations.RemoveField(
            model_name='team',
            name='icons12',
        ),
    ]
