# Generated by Django 2.2.2 on 2019-06-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fusion', '0012_auto_20190626_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='icons12',
            field=models.CharField(choices=[('fa fa-instagram', 'insta'), ('lni-facebook-filled', 'facebook'), ('lni-instagram-filled', 'twitter')], default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='icons13',
            field=models.CharField(choices=[('fa fa-instagram', 'insta'), ('lni-facebook-filled', 'facebook'), ('lni-instagram-filled', 'twitter')], default=1, max_length=200),
            preserve_default=False,
        ),
    ]
