# Generated by Django 2.2.2 on 2019-06-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fusion', '0014_auto_20190626_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='icons2',
            field=models.CharField(choices=[('lni-package', 'insta'), ('lni-drop', 'facebook'), ('lni-star', 'twitter')], max_length=100),
        ),
    ]
