# Generated by Django 2.2.2 on 2019-06-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fusion', '0016_auto_20190626_0809'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=2000)),
                ('phono', models.IntegerField()),
                ('email', models.EmailField(max_length=1000)),
            ],
        ),
    ]
