# Generated by Django 2.2.2 on 2019-06-26 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fusion', '0017_footercontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='footercontact',
            name='h',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
