# Generated by Django 2.2.2 on 2019-06-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fusion', '0018_footercontact_h'),
    ]

    operations = [
        migrations.CreateModel(
            name='Copyright',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2000)),
                ('email', models.EmailField(max_length=1000)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
