# Generated by Django 2.2.2 on 2019-06-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fusion', '0019_copyright'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='copyright',
            name='email',
        ),
        migrations.AddField(
            model_name='copyright',
            name='link',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
