# Generated by Django 2.2.2 on 2019-06-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fusion', '0020_auto_20190626_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Heading', models.CharField(help_text='Enter heading', max_length=200)),
                ('description', models.CharField(help_text='Enter heading', max_length=200)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
