# Generated by Django 2.2.2 on 2019-06-27 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fusion', '0021_home'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name3',
            new_name='name',
        ),
    ]
