# Generated by Django 2.2.2 on 2019-06-27 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fusion', '0023_auto_20190627_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='subject',
        ),
    ]
